version: '3'

services:
  api:
    container_name: slip-validate
    build:
      context: .
      dockerfile: Dockerfile
    volumes :
      - /app/node_modules
      - .:/app
    ports:
      - "5000:5000"
    command:  bash -c "cd /app && npm install && npm start"
    deploy:
      resources:
        limits:
          memory: 2G