version: '3'

services:
  api:
    container_name: slip-validate
    image: thutgtz/slip-validate:dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes :
      - /app/node_modules
      - .:/app
    ports:
      - "5000:5000"
    command: npm test