version: '3'

services:
  api:
    container_name: slip-validate
    build:
      context: .
      dockerfile: Dockerfile
    command:  bash -c "npm install && npm start"
    volumes :
      - .:/app
    ports:
      - "5000:5000"