version: '3'

services:
  api:
    container_name: slip-validate
    build:
      context: .
      dockerfile: Dockerfile
    command: node .\index.js
    volumes :
      - ${PWD}:/app
    ports:
      - "5000:5000"