version: '3'

services:
  api:
    container_name: slip-validate
    image: thutgtz/slip-validate:0.1
    build:
      context: .
      dockerfile: Dockerfile
    volumes :
      - /app/node_modules
      - .:/app
    ports:
      - "5000:5000"
    command: npm start
    # deploy:
    #   resources:
    #     limits:
    #       memory: 2G