version: '3'

services:
  api:
    container_name: slip-validate
    build:
      context: .
      dockerfile: Dockerfile
    volumes :
      - /app/node_modules
      - .:/app
    ports:
      - "5000:5000"
    command:  bash -c "cd /app && npm install -g nodemon --unsafe-perm=true --allow-root && npm install && npm start"
