version: '3'

services:
  api:
    container_name: slip-validate
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -F anything
    volumes :
      - .:/app
    ports:
      - "5000:5000"